sudo: required

services:
  - docker

env:
  global:
    - appUser="media"
    - appGroup="1000"

install:
  - docker build --rm --no-cache -t cryptout/couchpotato ../couchpotato

script:
  - ./rundocker.sh
  - sleep 10
  - bats tests/

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push USER/REPO;
    fi

notifications:
  email: false
